name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Define the runner environment

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

     

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-image:latest .

      

      # Run Docker container (you can also run tests in the container)
      - name: Run Docker container
        run: |
          docker run -d --name my-container my-image:latest
          docker ps  # Display running containers

      # Clean up Docker containers
      - name: Clean up Docker containers
        run: |
          docker stop my-container
          docker rm my-container
