name: Build Node.js Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (without pushing)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # Don't push to any registry
          tags: nodejs-app:local  # Just a local tag

